// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xrlqxncccdrjlfhbqcli.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhybHF4bmNjY2RyamxmaGJxY2xpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4Nzk1MDgsImV4cCI6MjA2MzQ1NTUwOH0.C-QYIwoUJ49ZbsarkQxBe4Si4xhBWU8S2bz5m1cEWnE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);